app:
  baseUrl: ${NFS_BASE_URL:-http://localhost:7007}
  packageName: app-next
  packages: all

backend:
  baseUrl: ${NFS_BASE_URL:-http://localhost:7007}
  cors:
    origin: ${NFS_BASE_URL:-http://localhost:7007}

catalog:
  locations:
    - type: file
      target: ${NFS_KUBERNETES_FIXTURE:-../../packages/app-next/fixtures/kubernetes-control.yaml}

kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters: []
