# syntax=docker/dockerfile:1.7-labs
# DevPortal unified image
#
# Follows the canonical Backstage build pattern: heavy compilation (yarn install,
# tsc, webpack) runs on the host or CI runner — NOT inside `docker build`. The
# image only packages pre-built artefacts.
#
# PREREQUISITE — before `docker build`, generate the artefacts on the host:
#   yarn install --immutable
#   yarn build:backend     # → packages/backend/dist/skeleton.tar.gz + bundle.tar.gz
#
# Local build (orchestrated — handles both steps):
#   ./scripts/build-local-image.sh

# Red Hat publishes UBI on two registries: `registry.redhat.io` (authenticated)
# and `registry.access.redhat.com` (anonymous, UBI-only mirror). Same image
# bit-for-bit. We pull from the anonymous mirror so no Red Hat credentials are
# needed in CI, forks, or contributor laptops. See docs/adr/012-anonymous-ubi-mirror.md.
#
# Runtime base: ubi10/nodejs-22-minimal ships node+npm but NO build toolchain
# (make/gcc/g++ absent, microdnf instead of dnf). The only native module
# (better-sqlite3) installs a prebuilt binary via `yarn workspaces focus`, so
# nothing compiles here. Pinned by digest for reproducible multi-arch builds.
ARG NODE_BASE_RUNTIME=registry.access.redhat.com/ubi10/nodejs-22-minimal:10.1@sha256:ddd89a0893420dc94698d10325c664eb900c61c4c5eb4e839b93a0cd27f34668

# Pinned versions of CLI binaries shipped in the runtime image.
ARG YQ_VERSION=4.53.2
ARG DECK_VERSION=1.59.1
ARG KUBECTL_VERSION=v1.36.0

# allows setting NPM registry from build arg (for mirrors / offline)
ARG NPM_REGISTRY=https://registry.npmjs.org/

# ============================================================================
# Runtime image — packages pre-built artefacts, installs production deps only
# ============================================================================
FROM ${NODE_BASE_RUNTIME}

USER root

ARG YQ_VERSION
ARG DECK_VERSION
ARG KUBECTL_VERSION

# Runtime packages. NO build toolchain / *-devel: nothing compiles here.
# `python`/`python3` symlinked to 3.12 because install-dynamic-plugins.sh
# calls bare `python` and the minimal base ships no `alternatives`.
# yq fetched with curl (no wget on minimal), arch-aware.
RUN ARCH="$(arch | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')" && \
    microdnf install -y --nodocs --setopt=install_weak_deps=0 \
      skopeo git jq tar gzip ca-certificates \
      python3.12 python3.12-pip && \
    microdnf clean all && rm -rf /var/cache/dnf /var/cache/yum /var/cache/libdnf5 && \
    ln -sf /usr/bin/python3.12 /usr/bin/python3 && \
    ln -sf /usr/bin/python3.12 /usr/bin/python && \
    curl -fsSL "https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_${ARCH}" \
      -o /usr/local/bin/yq && \
    chmod +x /usr/local/bin/yq

RUN ARCH=$(arch | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/') && \
    curl -sL "https://github.com/kong/deck/releases/download/v${DECK_VERSION}/deck_${DECK_VERSION}_linux_${ARCH}.tar.gz" -o /tmp/deck.tar.gz && \
    tar -xf /tmp/deck.tar.gz -C /tmp && \
    mv /tmp/deck /usr/local/bin/ && \
    chmod +x /usr/local/bin/deck && \
    rm /tmp/deck.tar.gz

RUN ARCH=$(arch | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/') && \
    curl -sLO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${ARCH}/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

# Python deps for techdocs (mkdocs)
COPY python /opt/python
RUN --mount=type=cache,target=/root/.cache/pip \
    cd /opt/python/ && \
    python3.12 -m pip install --upgrade pip setuptools pyyaml && \
    python3.12 -m pip install -r requirements.txt --ignore-installed urllib3 && \
    mkdocs --version

# corepack must run as root — global npm prefix (/usr/lib/node_modules) is
# root-owned on UBI minimal and uid 1001 cannot write to it.
RUN npm install -g corepack && corepack enable && corepack prepare yarn@4.12.0 --activate

# The root step above seeds $HOME/.npm (HOME=/opt/app-root/src) root-owned; hand the
# home cache dirs to uid 1001 so prebuild-install can write its prebuilt-binary cache
# during `yarn workspaces focus` instead of falling back to node-gyp (which has no
# toolchain here and fails: better-sqlite3, keytar, isolated-vm).
RUN mkdir -p /opt/app-root/src/.npm /opt/app-root/src/.cache && \
    chown -R 1001:0 /opt/app-root/src/.npm /opt/app-root/src/.cache

USER 1001
WORKDIR /app

ARG NPM_REGISTRY
ENV NPM_REGISTRY=$NPM_REGISTRY \
    NPM_CONFIG_REGISTRY=$NPM_REGISTRY \
    YARN_REGISTRY=$NPM_REGISTRY \
    NODE_ENV=production \
    NODE_OPTIONS="--no-node-snapshot"

# Skeleton install (dependency manifests only, then production install).
# skeleton.tar.gz and bundle.tar.gz are generated by `yarn build:backend` on the
# host/CI before `docker build` is invoked. They are bind-mounted (not COPY'd) so
# the tarballs never land in a layer — a COPY+rm would leave them in the COPY layer.
COPY --chown=1001:0 .yarn ./.yarn
COPY --chown=1001:0 yarn.lock package.json backstage.json ./
RUN --mount=type=bind,source=packages/backend/dist/skeleton.tar.gz,target=/tmp/skeleton.tar.gz \
    tar xzf /tmp/skeleton.tar.gz

RUN yarn config set npmRegistryServer "$NPM_REGISTRY" && \
    yarn config set nodeLinker node-modules && \
    if [ "$NPM_REGISTRY" != "https://registry.npmjs.org/" ]; then \
      HOST=$(printf '%s\n' "$NPM_REGISTRY" | awk -F[/:] '{print $4}') && \
      yarn config set unsafeHttpWhitelist --json "[\"localhost\",\"$HOST\"]"; \
    fi && \
    cp .yarnrc.yml $HOME/.yarnrc.yml

RUN --mount=type=cache,target=/opt/app-root/src/.yarn/berry/cache,sharing=locked,uid=1001,gid=0 \
    --mount=type=cache,target=/opt/app-root/src/.yarn/berry/index,sharing=locked,uid=1001,gid=0 \
    yarn workspaces focus --all --production

# Fail fast if a required native module didn't get its prebuilt binary
# (cpu-features is optional and may be skipped; the sqlite driver is not).
RUN node -e "require('better-sqlite3'); console.log('native deps OK: better-sqlite3 loaded')"

# Backend bundle
RUN --mount=type=bind,source=packages/backend/dist/bundle.tar.gz,target=/tmp/bundle.tar.gz \
    tar xzf /tmp/bundle.tar.gz

# Runtime configs and policies
COPY --chown=1001:0 examples ./examples
COPY --chown=1001:0 rbac-policy.csv /app/
COPY --chown=1001:0 rbac-policy-extensions.csv /tmp/
RUN cat /tmp/rbac-policy-extensions.csv >> /app/rbac-policy.csv && rm /tmp/rbac-policy-extensions.csv

COPY --chown=1001:0 app-config.yaml app-config.production.yaml app-config.distro.yaml ./

# Bake the small set of npm-published plugins into the image at the path
# install-dynamic-plugins.py expects (preInstalled:true entries in
# dynamic-plugins.default.yaml). Everything else loads via OCI refs at boot.
COPY --chown=1001:0 docker/download-baked-plugins.sh docker/baked-plugins.json ./docker/
RUN ./docker/download-baked-plugins.sh /app/dynamic-plugins-root

# Defensive: install-dynamic-plugins.py writes into this dir at boot.
# /app/data holds the persistent sqlite database (app-config.production.yaml).
RUN mkdir -p /app/dynamic-plugins-root /app/data

# Declare /app/data as a volume so `docker run` without an explicit -v still
# gets an anonymous volume mounted here. Marketplace state survives a
# `docker stop/start` cycle. For persistence across container recreation,
# operators need a named volume (or use the shipped docker-compose.yml).
VOLUME /app/data

# Pull the marketplace's catalog-backend-module-extensions from the RHDH extensions OCI.
# That module registers extensions.backstage.io/v1alpha1 entity kinds and ingests the
# plugin-catalog-index into the catalog, which the marketplace queries.
#
# bs_1.49.4 build imports `catalogProcessingExtensionPoint` from
# `@backstage/plugin-catalog-node/alpha`, which Backstage 1.50 graduated to the main
# export — so on a 1.50 backend that alpha import is `undefined` and the catalog plugin
# crashes. STOPGAP: patch the built module.cjs.js to fall back to the main export when
# `/alpha` lacks `catalogProcessingExtensionPoint`.
#
# TODO: once quay.io/veecode/extensions:bs_1.50.0 is published, set EXTENSIONS_TAG=bs_1.50.0
# and drop the sed patch (it self-skips if the /alpha import is absent).
ARG EXTENSIONS_TAG=bs_1.49.4
RUN set -e; \
    OCI_IMAGE="docker://quay.io/veecode/extensions:$EXTENSIONS_TAG"; \
    TMP_OCI="$(mktemp -d)"; \
    TMP_EXTRACT="$(mktemp -d)"; \
    if skopeo copy "$OCI_IMAGE" "dir:$TMP_OCI" 2>/dev/null; then \
      LAYER=$(jq -r '.layers[0].digest' "$TMP_OCI/manifest.json" | sed 's/sha256://'); \
      tar -xzf "$TMP_OCI/$LAYER" -C "$TMP_EXTRACT"; \
      cp -a "$TMP_EXTRACT/red-hat-developer-hub-backstage-plugin-catalog-backend-module-extensions" /app/dynamic-plugins-root/; \
      MOD=/app/dynamic-plugins-root/red-hat-developer-hub-backstage-plugin-catalog-backend-module-extensions/dist/module.cjs.js; \
      if grep -q "plugin-catalog-node/alpha" "$MOD"; then \
        sed -i "s|var alpha = require('@backstage/plugin-catalog-node/alpha');|var alpha = require('@backstage/plugin-catalog-node/alpha'); if (!alpha.catalogProcessingExtensionPoint) alpha = Object.assign({}, alpha, require('@backstage/plugin-catalog-node'));|" "$MOD"; \
        grep -q "Object.assign" "$MOD" || { echo "ERROR: catalogProcessingExtensionPoint /alpha->main patch did not apply to $MOD"; exit 1; }; \
        echo "patched catalog-backend-module-extensions (/alpha -> main catalogProcessingExtensionPoint fallback)"; \
      fi; \
    else \
      echo "WARN: failed to fetch RHDH extensions OCI image $OCI_IMAGE — skipping"; \
    fi; \
    rm -rf "$TMP_OCI" "$TMP_EXTRACT"

# Plugin install scripts + config files consumed at startup
COPY --chown=1001:0 dynamic-plugins.yaml dynamic-plugins.default.yaml /app/
COPY --chown=1001:0 presets /app/presets
COPY --chown=1001:0 docker/install-dynamic-plugins.py /app/install-dynamic-plugins.py
COPY --chown=1001:0 --chmod=755 docker/install-dynamic-plugins.sh /app/install-dynamic-plugins.sh

# Marketplace catalog entities — bake a snapshot from the OCI catalog index so
# every fresh container starts ready (~157KB tarball, ~220 YAMLs as of bs_1.49.4).
# The entrypoint's PACKAGES_COUNT guard skips the runtime download when present.
# Operators force a refresh with CATALOG_INDEX_REFRESH=true.
ARG CATALOG_INDEX_IMAGE=quay.io/veecode/plugin-catalog-index:latest
RUN set -e; \
    mkdir -p /app/catalog-entities/extensions/plugins \
             /app/catalog-entities/extensions/packages \
             /app/catalog-entities/extensions/collections; \
    TMP_CATALOG="$(mktemp -d)"; \
    skopeo copy "docker://${CATALOG_INDEX_IMAGE}" "dir:$TMP_CATALOG"; \
    LAYER=$(jq -r '.layers[0].digest' "$TMP_CATALOG/manifest.json" | sed 's/sha256://'); \
    tar -xf "$TMP_CATALOG/$LAYER" -C /app/catalog-entities/extensions --strip-components=1 2>/dev/null \
      || tar -xzf "$TMP_CATALOG/$LAYER" -C /app/catalog-entities/extensions --strip-components=1; \
    YAML_COUNT=$(find /app/catalog-entities/extensions -name '*.yaml' | wc -l); \
    echo "Baked catalog index: $YAML_COUNT YAMLs from $CATALOG_INDEX_IMAGE"; \
    rm -rf "$TMP_CATALOG"

# Version stamp consumed by the about plugin
ARG DEVPORTAL_VERSION=dev
RUN echo "{\"version\":\"${DEVPORTAL_VERSION}\"}" > /app/devportal.json

# Entrypoint
COPY --chown=1001:0 --chmod=755 entrypoint.sh /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.production.yaml", "--config", "/app/dynamic-plugins-root/app-config.dynamic-plugins.yaml"]
