#!/usr/bin/env bash
# NFS tracer bench (T1.0a) — bring up / tear down the minimal bench.
#
# Minimal means: the NFS host image plus a real Postgres plus the marketplace
# catalog fixture. No k3d, no MinIO — the tracer does not use them.
#
# Usage:
#   ./bench.sh up               # start, wait for health, print a summary
#   ./bench.sh down             # stop and remove (state is tmpfs, so nothing survives)
#   ./bench.sh status           # container + health state
#   ./bench.sh logs [-f]        # host logs
#   ./bench.sh psql [args...]   # psql inside the postgres container
#   ./bench.sh entities         # what the catalog actually ingested from the fixture
#
#   -n <name>   run an independent named instance (ports derived from the name,
#               so several benches coexist). Default instance is "nfs-tracer".
#
# Examples:
#   ./bench.sh up
#   ./bench.sh -n t13 up            # a second bench for T1.3, its own ports and DB
#   ./bench.sh -n t13 psql -c '\dt'
#
# Ports: default 17707 (host) / 15432 (postgres). A named instance offsets both
# by a stable hash of its name, so `-n t13` always lands on the same pair.
#
# Every image is pinned by digest in docker-compose.yaml. Versions and the digest
# rationale are in README.md.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

INSTANCE='nfs-tracer'
while getopts ':n:' opt; do
  case "$opt" in
    n) INSTANCE="$OPTARG" ;;
    :) echo "error: -$OPTARG needs a value" >&2; exit 2 ;;
    ?) echo "error: unknown flag -$OPTARG" >&2; exit 2 ;;
  esac
done
shift $((OPTIND - 1))

CMD="${1:-}"; shift || true

# Derive a stable port pair from the instance name so named benches never collide.
# The default instance keeps the documented 17707/15432 for reproducibility.
if [[ "$INSTANCE" == 'nfs-tracer' ]]; then
  OFFSET=0
else
  OFFSET=$(( ( 0x$(printf '%s' "$INSTANCE" | md5sum | cut -c1-4) % 100 ) + 1 ))
fi

export BENCH_PROJECT="$INSTANCE"
export COMPOSE_PROJECT_NAME="$INSTANCE"
export BENCH_HTTP_PORT="${BENCH_HTTP_PORT:-$(( 17707 + OFFSET * 2 ))}"
export BENCH_PG_PORT="${BENCH_PG_PORT:-$(( 15432 + OFFSET * 2 ))}"
export BENCH_PG_USER="${BENCH_PG_USER:-devportal}"
export BENCH_PG_PASSWORD="${BENCH_PG_PASSWORD:-devportal}"
export BENCH_PG_DATABASE="${BENCH_PG_DATABASE:-backstage}"

BASE_URL="http://localhost:${BENCH_HTTP_PORT}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-240}"

compose() { docker compose "$@"; }

# Where a locally built catalog module is expected. Without it the Plugin/Package
# kinds have no processor and the catalog REJECTS the fixture outright — measured,
# see README § "Why the module is not optional".
MODULE_DIR='artifacts/catalog-backend-module-extensions'

# The kubernetes control remote, opt-in with BENCH_WITH_K8S_REMOTE=1. This is the
# same artifact the 2026-07-29 Gate 1 run used, and it exists for one reason: every
# core surface on this bench is served by a STATICALLY discovered package, so a
# green run says nothing about the Module Federation host path. This plugin is
# deliberately absent from app.packages.include, so anything it renders can only
# have arrived through the loader. Pair it with
# NFS_SHELL_REMOTE_ROUTE in the smoke to assert that.
K8S_REMOTE='oci://quay.io/veecode/backstage:bs_1.53.0!backstage-plugin-kubernetes'

# Regenerate the inventory the entrypoint will read. Always writes a valid file so
# the compose mount never dangles.
write_inventory() {
  mkdir -p .generated artifacts
  if [[ -f "${MODULE_DIR}/package.json" ]]; then
    cat > .generated/dynamic-plugins.yaml <<'YAML'
# GENERATED by bench.sh — do not edit, do not commit.
plugins:
  - package: ./bench-artifacts/catalog-backend-module-extensions
    disabled: false
YAML
    MODE='with-catalog-module'
  else
    cat > .generated/dynamic-plugins.yaml <<'YAML'
# GENERATED by bench.sh — do not edit, do not commit.
# No local artifact present, so the host boots with an empty inventory. The
# Plugin/Package fixture will be REJECTED in this mode. Run `./bench.sh fetch` first.
plugins: []
YAML
    MODE='empty-host'
  fi
  if [[ "${BENCH_WITH_K8S_REMOTE:-0}" == '1' ]]; then
    # `plugins: []` is a valid empty sequence, so appending an item to it would
    # produce invalid YAML. Replace the marker instead when that is the shape.
    if grep -qx 'plugins: \[\]' .generated/dynamic-plugins.yaml; then
      sed -i 's|^plugins: \[\]$|plugins:|' .generated/dynamic-plugins.yaml
    fi
    cat >> .generated/dynamic-plugins.yaml <<YAML
  - package: '${K8S_REMOTE}'
    disabled: false
YAML
    MODE="${MODE}+k8s-remote"
  fi
}

wait_healthy() {
  local deadline=$(( SECONDS + HEALTH_TIMEOUT ))
  local state
  while (( SECONDS < deadline )); do
    state="$(docker inspect -f '{{.State.Health.Status}}' "${INSTANCE}-devportal-1" 2>/dev/null || echo 'missing')"
    case "$state" in
      healthy) return 0 ;;
      unhealthy)
        echo "  host went unhealthy after $(( SECONDS ))s" >&2
        return 1
        ;;
    esac
    # A crashed container never turns unhealthy, it just stops. Catch that too,
    # otherwise we sit here until the timeout for a boot that already failed.
    if [[ "$(docker inspect -f '{{.State.Running}}' "${INSTANCE}-devportal-1" 2>/dev/null || echo true)" == 'false' ]]; then
      echo "  host exited during boot (code $(docker inspect -f '{{.State.ExitCode}}' "${INSTANCE}-devportal-1"))" >&2
      return 1
    fi
    sleep 3
  done
  echo "  timed out after ${HEALTH_TIMEOUT}s waiting for health" >&2
  return 1
}

case "$CMD" in
  fetch)
    # Pull the exported catalog module out of a CI run and unpack it for the
    # local-path loader. Nothing is published to any registry by this.
    RUN_ID="${1:-30951225286}"
    REPO='veecode-platform/devportal-plugin-export-overlays'
    mkdir -p artifacts
    art_id="$(gh api "repos/${REPO}/actions/runs/${RUN_ID}/artifacts" \
      --jq '.artifacts[] | select(.name | startswith("dynamic plugin packages")) | .id' | head -1)"
    if [[ -z "$art_id" ]]; then
      echo "no 'dynamic plugin packages' artifact on run ${RUN_ID}" >&2
      exit 1
    fi
    tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
    gh api "repos/${REPO}/actions/artifacts/${art_id}/zip" > "$tmp/a.zip"
    unzip -o -q "$tmp/a.zip" -d "$tmp"
    tgz="$(find "$tmp" -name '*catalog-backend-module-extensions*.tgz' | head -1)"
    if [[ -z "$tgz" ]]; then
      echo "run ${RUN_ID} has no catalog-backend-module-extensions package" >&2
      exit 1
    fi
    rm -rf "$MODULE_DIR"; mkdir -p "$MODULE_DIR"
    # npm pack wraps everything in package/, strip it so package.json is at the root.
    tar -xzf "$tgz" -C "$MODULE_DIR" --strip-components=1
    ver="$(python3 -c "import json;print(json.load(open('${MODULE_DIR}/package.json'))['version'])")"
    echo "unpacked catalog-backend-module-extensions ${ver} from run ${RUN_ID}"
    ;;

  up)
    write_inventory
    echo "instance : ${INSTANCE}"
    echo "host     : ${BASE_URL}"
    echo "postgres : localhost:${BENCH_PG_PORT} (db ${BENCH_PG_DATABASE}, user ${BENCH_PG_USER})"
    echo "mode     : ${MODE}"
    if [[ "$MODE" == 'empty-host' ]]; then
      echo "           (no local catalog module — the Plugin/Package fixture WILL be rejected;"
      echo "            run './bench.sh fetch' to load it)"
    fi
    echo
    compose up -d --wait-timeout 5 postgres
    compose up -d devportal
    echo "waiting for readiness ..."
    if ! wait_healthy; then
      echo
      echo "last 40 host log lines:" >&2
      compose logs --tail 40 devportal >&2 || true
      exit 1
    fi
    echo "  healthy"
    echo
    # The log line is JSON, so match the message text and print just that.
    echo "database in effect:"
    compose logs devportal 2>/dev/null \
      | grep -oiE 'Database is (PostgreSQL|SQLite)[^"]*' | sort -u | sed 's/^/  /' \
      || echo "  (no database line found in logs)"
    echo
    echo "marketplace fixture entities in the catalog:"
    "$0" -n "$INSTANCE" entities | sed 's/^/  /'
    ;;

  down)
    # -v drops the named volumes too. Postgres data is tmpfs anyway, so a bench
    # is disposable by construction: the next `up` always starts empty.
    compose down -v --remove-orphans
    echo "instance ${INSTANCE} removed"
    ;;

  status)
    compose ps
    ;;

  logs)
    compose logs "$@" devportal
    ;;

  psql)
    docker exec -i "${INSTANCE}-postgres-1" \
      psql -U "$BENCH_PG_USER" -d "${BENCH_PG_DATABASE}" "$@"
    ;;

  entities)
    # Guest auth is what app-config.yaml ships, so this needs no secret.
    token="$(curl -fsS -X POST "${BASE_URL}/api/auth/guest/refresh" \
      -H 'Content-Type: application/json' -d '{}' 2>/dev/null \
      | python3 -c 'import json,sys; print(json.load(sys.stdin)["backstageIdentity"]["token"])' 2>/dev/null || true)"
    if [[ -z "$token" ]]; then
      echo "could not obtain a guest token — is the bench up?" >&2
      exit 1
    fi
    curl -fsS -H "Authorization: Bearer ${token}" \
      "${BASE_URL}/api/catalog/entities?filter=kind=plugin&filter=kind=package" 2>/dev/null \
      | python3 lib/show-entities.py
    ;;

  *)
    sed -n '2,30p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 2
    ;;
esac
