import { DynamicPluginInfo } from '../api/types';

// Plugin names recognised as "internal" (shipped with the image) for the
// dynamic-plugins-info UI. Used only for visual classification — a plugin
// in this set is rendered with the "internal" badge regardless of how it
// was actually loaded (OCI bundle, npm pack, or local extract).
export const InternalPluginsMap: ReadonlySet<string> = new Set([
  'backstage-community-plugin-3scale-backend-dynamic',
  'backstage-community-plugin-acr',
  'backstage-community-plugin-analytics-provider-segment',
  'backstage-community-plugin-azure-devops',
  'backstage-community-plugin-azure-devops-backend-dynamic',
  'backstage-community-plugin-catalog-backend-module-keycloak-dynamic',
  'backstage-community-plugin-catalog-backend-module-pingidentity-dynamic',
  'backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor-dynamic',
  'backstage-community-plugin-dynatrace',
  'backstage-community-plugin-github-actions',
  'backstage-community-plugin-github-issues',
  'backstage-community-plugin-jenkins',
  'backstage-community-plugin-jenkins-backend-dynamic',
  'backstage-community-plugin-jfrog-artifactory',
  'backstage-community-plugin-lighthouse',
  'backstage-community-plugin-nexus-repository-manager',
  'backstage-community-plugin-ocm',
  'backstage-community-plugin-ocm-backend-dynamic',
  'backstage-community-plugin-quay',
  'backstage-community-plugin-rbac',
  'backstage-community-plugin-redhat-argocd',
  'backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic',
  'backstage-community-plugin-scaffolder-backend-module-quay-dynamic',
  'backstage-community-plugin-scaffolder-backend-module-regex-dynamic',
  'backstage-community-plugin-scaffolder-backend-module-servicenow-dynamic',
  'backstage-community-plugin-scaffolder-backend-module-sonarqube-dynamic',
  'backstage-community-plugin-sonarqube',
  'backstage-community-plugin-sonarqube-backend-dynamic',
  'backstage-community-plugin-tech-radar',
  'backstage-community-plugin-tech-radar-backend-dynamic',
  'backstage-community-plugin-tekton',
  'backstage-community-plugin-topology',
  'backstage-plugin-catalog-backend-module-bitbucket-cloud-dynamic',
  'backstage-plugin-catalog-backend-module-bitbucket-server-dynamic',
  'backstage-plugin-catalog-backend-module-github-dynamic',
  'backstage-plugin-catalog-backend-module-github-org-dynamic',
  'backstage-plugin-catalog-backend-module-gitlab-dynamic',
  'backstage-plugin-catalog-backend-module-gitlab-org-dynamic',
  'backstage-plugin-catalog-backend-module-ldap-dynamic',
  'backstage-plugin-catalog-backend-module-msgraph-dynamic',
  'backstage-plugin-kubernetes',
  'backstage-plugin-kubernetes-backend-dynamic',
  'backstage-plugin-notifications',
  'backstage-plugin-notifications-backend-dynamic',
  'backstage-plugin-notifications-backend-module-email-dynamic',
  'backstage-plugin-scaffolder-backend-module-azure-dynamic',
  'backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic',
  'backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic',
  'backstage-plugin-scaffolder-backend-module-gerrit-dynamic',
  'backstage-plugin-scaffolder-backend-module-github-dynamic',
  'backstage-plugin-scaffolder-backend-module-gitlab-dynamic',
  'backstage-plugin-signals',
  'backstage-plugin-signals-backend-dynamic',
  'backstage-plugin-techdocs',
  'backstage-plugin-techdocs-backend-dynamic',
  'backstage-plugin-techdocs-module-addons-contrib',
  'devportal-marketplace-backend-dynamic',
  'devportal-marketplace-frontend-dynamic',
  'devportal-pending-changes-dynamic',
  'immobiliarelabs-backstage-plugin-gitlab-backend-dynamic',
  'pagerduty-backstage-plugin',
  'pagerduty-backstage-plugin-backend-dynamic',
  'parfuemerie-douglas-scaffolder-backend-module-azure-repositories-dynamic',
  'red-hat-developer-hub-backstage-plugin-adoption-insights',
  'red-hat-developer-hub-backstage-plugin-adoption-insights-backend-dynamic',
  'red-hat-developer-hub-backstage-plugin-analytics-module-adoption-insights-dynamic',
  'red-hat-developer-hub-backstage-plugin-bulk-import',
  'red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic',
  'red-hat-developer-hub-backstage-plugin-catalog-backend-module-marketplace-dynamic',
  'red-hat-developer-hub-backstage-plugin-dynamic-home-page',
  'red-hat-developer-hub-backstage-plugin-global-floating-action-button',
  'red-hat-developer-hub-backstage-plugin-global-header',
  'red-hat-developer-hub-backstage-plugin-marketplace',
  'red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic',
  'red-hat-developer-hub-backstage-plugin-quickstart',
  'roadiehq-backstage-plugin-argo-cd-backend-dynamic',
  'roadiehq-backstage-plugin-datadog',
  'roadiehq-backstage-plugin-github-insights',
  'roadiehq-backstage-plugin-github-pull-requests',
  'roadiehq-backstage-plugin-jira',
  'roadiehq-backstage-plugin-security-insights',
  'roadiehq-scaffolder-backend-argocd-dynamic',
  'roadiehq-scaffolder-backend-module-http-request-dynamic',
  'roadiehq-scaffolder-backend-module-utils-dynamic',
  'veecode-platform-plugin-veecode-theme',
]);

export const getNotEnabledInternalPlugins = (enabledPlugins: string[]) => {
  const plugins: DynamicPluginInfo[] = [];
  if (!enabledPlugins || enabledPlugins?.length === 0) return [];
  InternalPluginsMap.forEach(internalPlugin => {
    if (!enabledPlugins.includes(internalPlugin)) {
      plugins.push({
        name: internalPlugin,
        version: '',
        internal: true,
        enabled: false,
        role: '',
        platform: '',
      });
    }
  });
  return plugins;
};
